inherit_gem:
  caliber: config/all.yml

Metrics/AbcSize:
  Exclude:
    - "lib/hanamismith/builders/layout.rb"
Metrics/BlockLength:
  Exclude:
    - "lib/hanamismith/container.rb"
Metrics/ClassLength:
  Exclude:
    - "lib/hanamismith/cli/commands/build.rb"
Metrics/CollectionLiteralLength:
  Exclude:
    - "lib/hanamismith/cli/commands/build.rb"
Metrics/MethodLength:
  Exclude:
    - "lib/hanamismith/builders/layout.rb"
